development:
  :address: smtp.gmail.com
  :port: 25
  :Domain: mail.google.com
  :authentication: plain
  :user_name: priyanko.dey33@gmail.com
  :password: priyanko123456
  :enable_starttls_auto: true     

production:
  :address: smtp.live.com
  :port: 587
  :authentication: plain
  :user_name: info@rupeevest.com
  :password: betterment1234
  :enable_starttls_auto: true
